"""
Fetch company name + website domain for every ticker referenced in
funds-data.js, write to stock-info.js for use by fund.html.

Logos are loaded client-side from logo.clearbit.com using the domain.
"""

import re
import json
import time
import datetime as dt
from pathlib import Path
from curl_cffi import requests as curl_requests
import yfinance as yf

PROJECT  = Path("/Users/tre/Desktop/QBridge Site")
FUNDS_JS = PROJECT / "funds-data.js"
OUT_PATH = PROJECT / "stock-info.js"

SESSION = curl_requests.Session(impersonate="chrome")


def collect_tickers():
    text = FUNDS_JS.read_text()
    return sorted(set(re.findall(r'ticker:"([A-Z0-9.\-]+)"', text)))


def fetch_one(symbol):
    try:
        info = yf.Ticker(symbol, session=SESSION).info or {}
    except Exception:
        return {"name": "", "website": ""}
    return {
        "name":    (info.get("shortName") or info.get("longName") or "").strip(),
        "website": (info.get("website") or "").strip(),
    }


def domain_from_url(url):
    if not url:
        return ""
    m = re.match(r"^(?:https?://)?(?:www\.)?([^/]+)", url)
    return (m.group(1).lower() if m else "").rstrip("/")


def main():
    tickers = collect_tickers()
    print(f"Fetching info for {len(tickers)} tickers ...")

    out = {}
    misses = []
    for i, sym in enumerate(tickers, 1):
        if i % 25 == 0:
            print(f"  ... {i}/{len(tickers)}")
        rec  = fetch_one(sym)
        name = rec["name"]
        dom  = domain_from_url(rec["website"])
        out[sym] = {"name": name, "domain": dom}
        if not name:
            misses.append(sym)
        time.sleep(0.05)  # be gentle

    if misses:
        print(f"  no name for {len(misses)} tickers: {', '.join(misses)}")

    lines = [
        f"// Generated by fetch_stock_info.py at "
        f"{dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "// Per-ticker company name + website domain (for clearbit logo lookup).",
        "",
        "const STOCK_INFO = {",
    ]
    for sym in sorted(out):
        info = out[sym]
        lines.append(
            f"  {json.dumps(sym)}: {{ "
            f"name:{json.dumps(info['name'])}, "
            f"domain:{json.dumps(info['domain'])} }},"
        )
    lines.append("};")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"\nWrote {OUT_PATH} ({OUT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
