"""
Fetch historical price data via yfinance for each tracked ETF.

Daily closes (10y) and 1-minute intraday (7d) are written to prices-data.js,
which leveraged-etfs.html loads to populate the chart and the day-change
figures on each ETF card.

Re-run after adding new symbols to SYMBOLS or to refresh data.
"""

import yfinance as yf
import json
import time
import datetime as dt
from pathlib import Path
from curl_cffi import requests as curl_requests

# Keep in sync with ETF_DATA in leveraged-etfs.html
SYMBOLS = [
    "SPXL", "SPXS", "TNA", "TZA",
    "HIBL", "HIBS", "YINN", "YANG",
    "EDC", "EDZ", "LABU", "LABD",
    "FAS", "FAZ",
    "WEBL", "WEBS", "DRN", "DRV",
    "SOXL", "SOXS", "TECL", "TECS",
    "TYD", "TYO", "TMF", "TMV",
    "AIBU", "AIBD", "GUSH", "DRIP",
    "JNUG", "JDST", "NUGT", "DUST",
    "TQQQ", "SQQQ", "QLD", "QID",
    "AGQ", "ZSL", "EZJ", "EWV",
    "UGE", "SZK", "UBR", "BZQ",
    "UPW", "SDP", "UPV", "EPV",
    "UCC", "SCC", "YCL", "YCS",
    "UYM", "SMN", "ULE", "EUO",
    "UXI", "SIJ", "BOIL", "KOLD",
    "UJB", "SJB", "DIG", "DUG",
    "RXL", "RXD",
    "UGL", "GLL", "UYG", "SKF",
    # Single-direction (bull-only)
    "DPST", "TPOR", "RETL", "EURL",
    "MEXX", "KORU", "DFEN", "NAIL",
    "PILL", "CWEB", "INDL", "FNGG",
    "UBOT", "URAA", "QQQU",
    "LTL", "UCOP", "UCYB", "UPAL",
    "UPLT", "SKYU",
    # Single-stock leveraged pairs (Direxion 2X / -1X)
    "AAPU", "AAPD", "AMUU", "AMDD",
    "AMZU", "AMZD", "AVL",  "AVS",
    "CSCL", "CSCS", "GGLL", "GGLS",
    "METU", "METD", "MSFU", "MSFD",
    "MUU",  "MUD",  "NFXL", "NFXS",
    "NVDU", "NVDD", "ORCU", "ORCS",
    "PALU", "PALD", "PLTU", "PLTD",
    "QCMU", "QCMD", "TSLL", "TSLS",
    "TSMX", "TSMZ",
]

DAILY_PERIOD      = "10y"
INTRADAY_PERIOD   = "7d"
INTRADAY_INTERVAL = "1m"

OUT_PATH = Path("/Users/tre/Desktop/QBridge Site/prices-data.js")

# curl_cffi session impersonating Chrome dodges Yahoo's bot rate limits.
SESSION = curl_requests.Session(impersonate="chrome")


def fetch_daily(sym):
    df = yf.Ticker(sym, session=SESSION).history(
        period=DAILY_PERIOD, interval="1d", auto_adjust=False, actions=False
    )
    if df is None or df.empty:
        return []
    rows = []
    for ts, row in df.iterrows():
        close = float(row["Close"])
        if close > 0:
            rows.append([ts.strftime("%Y-%m-%d"), round(close, 2)])
    return rows


def fetch_intraday(sym):
    df = yf.Ticker(sym, session=SESSION).history(
        period=INTRADAY_PERIOD, interval=INTRADAY_INTERVAL,
        auto_adjust=False, actions=False, prepost=False,
    )
    if df is None or df.empty:
        return []
    rows = []
    for ts, row in df.iterrows():
        close = float(row["Close"])
        if close > 0:
            # Convert tz-aware timestamp to America/New_York local string
            try:
                ts_local = ts.tz_convert("America/New_York")
            except Exception:
                ts_local = ts
            rows.append([ts_local.strftime("%Y-%m-%d %H:%M"), round(close, 2)])
    return rows


def main():
    parts = [
        f"// Generated by fetch_prices.py at "
        f"{dt.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}Z",
        "// Re-run the script to refresh price history.",
        "",
        "const PRICES = {};",
        "",
    ]

    for sym in SYMBOLS:
        print(f"Fetching {sym} ...", flush=True)
        daily    = fetch_daily(sym)
        intraday = fetch_intraday(sym)
        print(f"  daily:    {len(daily):>5} points")
        print(f"  intraday: {len(intraday):>5} points")
        time.sleep(0.5)  # gentle pace between symbols
        parts.append(f"// ----- {sym} ({len(daily)} daily, {len(intraday)} intraday) -----")
        parts.append(f'PRICES["{sym}"] = {{')
        parts.append(f"  daily: "    + json.dumps(daily,    separators=(',', ':')) + ",")
        parts.append(f"  intraday: " + json.dumps(intraday, separators=(',', ':')))
        parts.append("};")
        parts.append("")

    OUT_PATH.write_text("\n".join(parts))
    print(f"\nWrote {OUT_PATH} ({OUT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
